### ISSUE TITLE
If used with bodyParser.urlencoded({extended:true}) file paths may be forged by an attacker

### ISSUE THREAD

**Issue by kornelski** [josefandersson/express-formparse#1]
If both multipart and urlencoded types of form are accepted, then an attacker can trick the application use an arbitrary local file instead of the uploaded one.

``` js
app.use(bodyParser.urlencoded({ extended: true }));
app.use(formparse.parse());

// Application assumes that 'file' field is an uploaded file:
app.post('/', (req, res) => res.sendFile(req.body.file.path));
```

However, the file upload can be faked by using `bodyParser` instead:

``` sh
curl app -d'file[path]=/etc/hosts' -Hcontent-type:application/x-www-form-urlencoded
```

I suggest using separate request property for files  (e.g. `req.files`), which isn't shared with other types of parsers.

**Comment by josefandersson** [comment]
Interesting, thanks. This didn't even cross my mind when I made it. Do you recon my latest push would fix this issue or am I completely missing your point? (Note that I have not used any other parsers. :s)

**Comment by kornelski** [comment]
Yup. dd356da6bf9dbafe8a3c62b0e3834984db767fe6 solves the problem!

**Comment by josefandersson** [comment]
Cool, thanks.
